version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_rotator:
    # This class handles the rotation
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  root:
    level: DEBUG
    handlers: [console, file_rotator]
    propagate: True
  cflib:
    level: DEBUG
    propagate: True
  paramiko:
    level: WARNING
    propagate: True
